/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WacAmbulanceWlList {
    }
}
declare global {
    interface HTMLWacAmbulanceWlListElement extends Components.WacAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLWacAmbulanceWlListElement: {
        prototype: HTMLWacAmbulanceWlListElement;
        new (): HTMLWacAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "wac-ambulance-wl-list": HTMLWacAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface WacAmbulanceWlList {
    }
    interface IntrinsicElements {
        "wac-ambulance-wl-list": WacAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wac-ambulance-wl-list": LocalJSX.WacAmbulanceWlList & JSXBase.HTMLAttributes<HTMLWacAmbulanceWlListElement>;
        }
    }
}
